apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
    capability.openshift.io/name: Console
spec:
  managementState: Managed
  customization:
    capabilities:
    - name: LightspeedButton
      visibility:
        state: Enabled
    - name: GettingStartedBanner
      visibility:
        state: Enabled
